FROM --platform=linux/amd64 node:20.17.0-alpine3.20 AS development

WORKDIR /usr/src/app

COPY --chown=node:node package.json ./
COPY --chown=node:node yarn.lock ./
COPY --chown=node:node prisma ./

RUN yarn install --frozen-lockfile

RUN yarn prisma generate

COPY --chown=node:node . .

USER node

FROM --platform=linux/amd64 node:20.17.0-alpine3.20 AS build

WORKDIR /usr/src/app

COPY --chown=node:node package.json ./
COPY --chown=node:node yarn.lock ./

COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules

COPY --chown=node:node . .

RUN yarn run build

ENV NODE_ENV production

USER node

FROM --platform=linux/amd64 node:20.17.0-alpine3.20 AS production

COPY --chown=node:node --from=build /usr/src/app/package.json ./package.json
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist

CMD [ "yarn", "run", "start:prod:rl-micro-comms" ]
