export const environment = {
  production: true,
  local: false,
  SNACKBAR_DURATION_MS: 5000,
  TOAST_DURATION_MS: 5000,
  STRIPE_LIFETIME_PAYMENT_URL: 'https://buy.stripe.com/8wM9E59zj6djb7icMU',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://buy.stripe.com/8wM03v7rb6dj4IU7sz',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://buy.stripe.com/28o17zcLv0SZ6R27sB',
  FRONT_END_URL: 'https://www.roomyledger.com',
  MAIN_API_URL: 'https://api.roomyledger.com/v1',
  SUPABASE_URL: 'https://infra.roomyledger.com/',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vY3FjYnpsY3dwb2h0d2ZpaHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTgwNjksImV4cCI6MjA1ODE5NDA2OX0.Dg3V85Nul8gMlDbRTg-oVmNMeNl4DVTr14yjXnRK9FI',
  ZENIGO_HOST: 'https://api.zenigo.io',
  ZENIGO_API_KEY: '746017eceb5ea6b075fba26ae7cfd365f8444466a2ab4f2e15a266fc9752238a',
  LOGIN_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/users',
  PAYMENTS_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/application-messages',
  USERS_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/notifications',
  PROPERTIES_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/ledgers/properties',
  EXPENSES_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/ledgers/expenses',
};
