export const environment = {
  production: true,
  local: false,
  SNACKBAR_DURATION_MS: 5000,
  TOAST_DURATION_MS: 5000,
  STRIPE_LIFETIME_PAYMENT_URL: 'https://checkout.roomyledger.com/b/8wM9E59zj6djb7icMU',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/8wM03v7rb6dj4IU7sz',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/28o17zcLv0SZ6R27sB',
  FRONT_END_URL: 'https://www.roomyledger.com',
  MAIN_API_URL: 'https://api.roomyledger.com/v1',
  SUPABASE_URL: 'https://auth.roomyledger.com/',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzM0MTM0NDAwLAogICJleHAiOiAxODkxOTAwODAwCn0.CllMzmo9fPYcH4GGFvtCLLl3kTLcjWC9vXLrTjsf7l0',
  FLAGSMITH_CLIENT_SDK_KEY: 'cphidq7nSp23dUzTRudS6H',
  FLAGSMITH_API_URL: 'https://flagsmith.roomyledger.com/api/v1/',
  LOGIN_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/users',
  PAYMENTS_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/application-messages',
  USERS_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/notifications',
  PROPERTIES_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/ledgers/properties',
  EXPENSES_SERVICE_BASE_URL: 'https://api.roomyledger.com/v1/ledgers/expenses',
};
