export const environment = {
  production: false,
  local: true,
  SNACKBAR_DURATION_MS: 5000,
  TOAST_DURATION_MS: 5000,
  STRIPE_LIFETIME_PAYMENT_URL: 'https://buy.stripe.com/test_aEU8zJdFu6cofrq5ko',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://buy.stripe.com/test_5kAbLV1WM9oAcfe9AG',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://buy.stripe.com/test_cN2dU358Y7gscfe5kp',
  FRONT_END_URL: 'http://localhost:4200',
  MAIN_API_URL: 'http://localhost:4200/api',
  SUPABASE_URL: 'https://yocvewguhpxbwtfidyfi.supabase.co',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvY3Zld2d1aHB4Ynd0ZmlkeWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDY1OTcsImV4cCI6MjA1ODgyMjU5N30.vb_3cf78snP0TzOVGQJZKaFT0BCFtRLMmW1P5yVSn-A',
  FLAGSMITH_CLIENT_SDK_KEY: '3Wiaxv5tfsbLEkarBYHf7o',
  FLAGSMITH_API_URL: 'https://flagsmith.roomyledger.com/api/v1/',
  PAYMENTS_SERVICE_BASE_URL: 'http://localhost:3000/v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'http://localhost:3000/v1/application-messages',
  USERS_SERVICE_BASE_URL: 'http://localhost:3000/v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'http://localhost:3000/v1/notifications',
  PROPERTIES_SERVICE_BASE_URL: 'http://localhost:3000/v1/ledgers/properties',
  EXPENSES_SERVICE_BASE_URL: 'http://localhost:3000/v1/ledgers/expenses',
};
