name: Verify Node.js

on:
  push:
    branches: [main, staging]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    name: Lint (v${{ matrix.node-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install
      - name: Lint (v${{ matrix.node-version }})
        run: yarn run lint

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    name: Build (v${{ matrix.node-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install
      - name: Build (v${{ matrix.node-version }})
        run: yarn run build

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    name: Test (v${{ matrix.node-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install
      - name: Test (v${{ matrix.node-version }})
        run: yarn run test

  sonarcloud-analysis:
    name: SonarCloud (v${{ matrix.node-version }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn run test:cov
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ matrix.project }}
          args: -Dsonar.projectKey=jonathanlee-io_rl-ledger-service
            -Dsonar.organization=jonathanlee-io
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.inclusions=**
            -Dsonar.exclusions=**/*.spec.ts,**.module.ts,src/main.ts
            -Dsonar.test.inclusions=src/**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.qualitygate.wait=true
