export const environment = {
  production: true,
  local: false,
  SNACKBAR_DURATION_MS: 5000,
  TOAST_DURATION_MS: 5000,
  STRIPE_LIFETIME_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_fZeg2b7h6dEQgvu7sv',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_eVaaHR30Q6co1AA5kl',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_bIY7vFgRGfMYbbacMO',
  FRONT_END_URL: 'https://staging.roomyledger.com',
  MAIN_API_URL: 'https://api.staging.roomyledger.com/v1',
  SUPABASE_URL: 'https://fmsbmfjxqisdphhbmggb.supabase.co/',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtc2JtZmp4cWlzZHBoaGJtZ2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQ3OTIxMzksImV4cCI6MjA0MDM2ODEzOX0.ENdgDBHl9a3K-8MNd0du0jKfgLSW6K2OjkypM-w2T-k',
  FLAGSMITH_CLIENT_SDK_KEY: 'NNs4ZnVzbfQo92qK7RmkAF',
  LOGIN_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/users',
  PAYMENTS_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/application-messages',
  USERS_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/notifications',
  PROPERTIES_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/ledgers/properties',
  EXPENSES_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/ledgers/expenses',
};
