export const environment = {
  production: false,
  local: true,
  SNACKBAR_DURATION_MS: 5000,
  TOAST_DURATION_MS: 5000,
  STRIPE_LIFETIME_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_aEU8zJdFu6cofrq5ko',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_5kAbLV1WM9oAcfe9AG',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_cN2dU358Y7gscfe5kp',
  FRONT_END_URL: 'http://localhost:4200',
  MAIN_API_URL: 'http://localhost:4200/api',
  SUPABASE_URL: 'https://gkuqhbshrqxeiitfapbq.supabase.co/',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrdXFoYnNocnF4ZWlpdGZhcGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQ3NjcxNjksImV4cCI6MjA0MDM0MzE2OX0.wBP27701Kh3gvjMpsOCDWS7NW1023hnqZwAah_TS8Ew',
  FLAGSMITH_CLIENT_SDK_KEY: 'NNs4ZnVzbfQo92qK7RmkAF',
  PAYMENTS_SERVICE_BASE_URL: 'http://localhost:3000/v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'http://localhost:3000/v1/application-messages',
  USERS_SERVICE_BASE_URL: 'http://localhost:3000/v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'http://localhost:3000/v1/notifications',
  PROPERTIES_SERVICE_BASE_URL: 'http://localhost:3000/v1/ledgers/properties',
  EXPENSES_SERVICE_BASE_URL: 'http://localhost:3000/v1/ledgers/expenses',
};
